require_relative "./clothing_store/version"
require_relative "./clothing_store/cli"
require_relative "./clothing_store/clothing_item"
require_relative "./clothing_store/ssense_scraper"
require_relative "./clothing_store/jcrew_scraper"
require_relative "./clothing_store/scraper"
require_relative "./clothing_store/store"
